version: '3'
services:
  npm:
    container_name: npm
    image: jc21/nginx-proxy-manager:latest
    ports:
      - '80:80'
      - '443:443'
    expose:
      - 81
    volumes:
      - /opt/appdata/npm/data:/data
      - /opt/appdata/npm/letsencrypt:/etc/letsencrypt
    environment:
      DB_MYSQL_HOST: mariadb
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: npm
      DB_MYSQL_NAME: npm
      DB_MYSQL_PASSWORD: "YOUR_MYSQL_NPM_DB_PASSWORD"
      DISABLE_IPV6: true
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    driver: bridge
    external: true