version: '3'
services:
  npm:
    container_name: npm
    image: jc21/nginx-proxy-manager:latest
    ports:
      - '80:80'
      - '443:443'
    expose:
      - 81
    volumes:
      - ${APP_DIR:?err}/npm/data:/data
      - ${APP_DIR:?err}/npm/letsencrypt:/etc/letsencrypt
    environment:
      DB_MYSQL_HOST: mariadb
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: ${MYSQL_NPM_USER}
      DB_MYSQL_NAME: ${MYSQL_NPM_NAME:?err}
      DB_MYSQL_PASSWORD: "${MYSQL_NPM_PASSWORD:?err}"
      DISABLE_IPV6: true
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    driver: bridge
    external: true