version: '3'
services:
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    expose:
      - 8989
    volumes:
      - ${APP_DIR:?err}/sonarr:/config
      - /mnt:/mnt
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr.entryPoints: https
      traefik.http.routers.sonarr.middlewares: auth@file
    environment:
      TZ: ${TZ:?err}
      PGID: ${ID:?err}
      PUID: ${ID:?err}
      UMASK: ${UMASK:?err}
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    driver: bridge
    external: true