version: '3'
services:
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    expose:
      - 8989
    volumes:
      - ${APP_DIR}/sonarr:/config
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr.entryPoints: https
      traefik.http.routers.sonarr.middlewares: auth@file
    environment:
      TZ: ${TZ}
      PGID: ${ID}
      PUID: ${ID}
      UMASK: ${UMASK}
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    driver: bridge
    external: true