version: '3'
services:
  tautulli:
    container_name: tautulli
    image: ${MAINTAINER:?err}/tautulli:latest
    expose:
      - 8181
    volumes:
      - ${APP_DIR:?err}/tautulli:/config
    labels:
      traefik.enable: true
      traefik.http.routers.tautulli.entryPoints: https
      traefik.http.routers.tautulli.middlewares: auth@file
    environment:
      TZ: ${TZ:?err}
      PGID: ${ID:?err}
      PUID: ${ID:?err}
      UMASK: ${UMASK:?err}
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    driver: bridge
    external: true
