version: '3'
services:
  overseerr:
    container_name: overseerr
    image: sctx/overseerr:latest
    expose:
      - 5055
    volumes:
      - ${APP_DIR}/overseerr:/app/config
    labels:
      traefik.enable: true
      traefik.http.routers.overseerr.entryPoints: https
    environment:
      TZ: ${TZ}
      PGID: ${ID}
      PUID: ${ID}
      UMASK: ${UMASK}
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    driver: bridge
    external: true