version: '3'
services:
  ombi:
    container_name: ombi
    image: linuxserver/ombi:latest
    expose:
      - 3579
    volumes:
      - /opt/appdata/ombi:/config
    labels:
      traefik.enable: true
      traefik.http.routers.ombi.entryPoints: https
      ## AUTHELIA Auth ##
      # traefik.http.routers.ombi.middlewares: auth@file
    environment:
      TZ: Europe/London
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    driver: bridge
    external: true