version: '3'
services:
  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:latest
    expose:
      - 9696
    volumes:
      - ${APP_DIR}/prowlarr:/config
    labels:
      traefik.enable: true
      traefik.http.routers.prowlarr.entryPoints: https
      traefik.http.routers.prowlarr.middlewares: auth@file
    environment:
      TZ: ${TZ}
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    driver: bridge
    external: true