version: '3'
services:
  plex:
    container_name: "plex"
    image: "${MAINTAINER:?err}/plex:latest"
    ports:
      - "32400:32400"
    volumes:
      - "${APP_DIR:?err}/plex/database:/config:rw"
      - "/mnt:/mnt:ro"
      - "${TRANSCODE_DIR:?err}:/transcode:rw"
    labels:
      traefik.enable: true
      traefik.http.routers.plex.entryPoints: https
    environment:
      TZ: ${TZ:?err}
      PGID: ${ID:?err}
      PUID: ${ID:?err}
      UMASK: ${UMASK:?err}
      PLEX_CLAIM: ${PLEX_CLAIM_ID:?err}
      VERSION: ${PLEX_VERSION:?err}
    networks:
      - proxy
    restart: unless-stopped
    extra_hosts:
      - "analytics.plex.tv:127.0.0.1"
      - "metrics.plex.tv:127.0.0.1"
      - "metric.plex.tv:127.0.0.1"
      - "mf.svc.nhl.com:127.0.0.1"
      - "mlb-ws-mf.media.mlb.com:127.0.0.1"
      - "playback.svcs.mlb.com:127.0.0.1"
    devices:
       - /dev/dri:/dev/dri

networks:
  proxy:
    driver: bridge
    external: true
