version: '3'
services:
  plex:
    container_name: "plex"
    environment:
      TZ: ${TZ}
      PGID: ${ID}
      PUID: ${ID}
      UMASK: ${UMASK}
      PLEX_CLAIM: ${PLEX_CLAIM_ID}
      VERSION: ${PLEX_VERSION}
    image: "linuxserver/plex:latest"
    restart: "unless-stopped"
    networks:
      - proxy
    extra_hosts:
      - "analytics.plex.tv:127.0.0.1"
      - "metrics.plex.tv:127.0.0.1"
      - "metric.plex.tv:127.0.0.1"
      - "mf.svc.nhl.com:127.0.0.1"
      - "mlb-ws-mf.media.mlb.com:127.0.0.1"
      - "playback.svcs.mlb.com:127.0.0.1"
    ports:
      - "32400:32400"
    volumes:
      - "${APP_DIR}/plex/database:/config:rw"
      - "/mnt:/mnt:ro"
      - "/dev/shm:/transcode:rw"
    devices:
       - /dev/dri:/dev/dri
    labels:
      traefik.enable: true
      traefik.http.routers.plex.entryPoints: https

networks:
  proxy:
    driver: bridge
    external: true
