version: '3'
services:
  auth:
    container_name: auth    
    image: authelia/authelia:latest
    expose:
      - 9091
    volumes:
      - ${APP_DIR:?err}/authelia:/config
    labels:
      traefik.enable: true
      traefik.http.routers.authelia.entryPoints: https
    networks:
      - proxy
      - secure
    restart: unless-stopped
    depends_on:
      - redis
      - mariadb

  redis:
    container_name: redis
    image: bitnami/redis:latest
    expose:
      - 6379
    volumes:
      - ${APP_DIR:?err}/redis:/bitnami/
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD:?err}"
    networks:
      - secure
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    image: linuxserver/mariadb:latest
    expose:
      - 3306
    volumes:
      - ${APP_DIR:?err}/mariadb:/config
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:?err}"    
    networks:
      - secure
    restart: unless-stopped

  openldap:
    container_name: openldap
    image: osixia/openldap:latest
    expose: 
      - 389
      - 636
    volumes:
      - ${APP_DIR:?err}/openldap/certificates:/container/service/slapd/assets/certs
      - ${APP_DIR:?err}/openldap/slapd/database:/var/lib/ldap
      - ${APP_DIR:?err}/openldap/slapd/config:/etc/ldap/slapd.d
    environment: 
      LDAP_ORGANISATION: "${LDAP_ORGANISATION:?err}"
      LDAP_DOMAIN: "${LDAP_DOMAIN:?err}"
      LDAP_ADMIN_USERNAME: "${LDAP_ADMIN_USERNAME:?err}"
      LDAP_ADMIN_PASSWORD: "${LDAP_ADMIN_PASSWORD:?err}"
      LDAP_CONFIG_PASSWORD: "${LDAP_CONFIG_PASSWORD:?err}"
      LDAP_BASE_DN: "${LDAP_BASE_DN:?err}"
      LDAP_TLS_CRT_FILENAME: "${LDAP_TLS_CRT_FILENAME:?err}"
      LDAP_TLS_KEY_FILENAME: "${LDAP_TLS_KEY_FILENAME:?err}"
      LDAP_TLS_CA_CRT_FILENAME: "${LDAP_TLS_CA_CRT_FILENAME:?err}"
    networks:
      - secure
    restart: unless-stopped
  
  ldapadmin:
    container_name: ldapadmin
    image: osixia/phpldapadmin:latest
    expose: 
      - 80
    labels:
      traefik.enable: true
      traefik.http.routers.ldapadmin.entryPoints: https
      traefik.http.routers.ldapadmin.middlewares: auth@file
    environment: 
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - openldap
    networks:
      - proxy
      - secure
    restart: unless-stopped

networks:
  proxy:
    driver: bridge
    external: true
  secure:
    driver: bridge
    external: true
