version: '3'
services:
  sabnzbd:
    container_name: sabnzbd
    image: linuxserver/sabnzbd:latest
    expose:
      - 7878
    volumes:
      - ${APP_DIR:?err}/sabnzbd:/config
    labels:
      traefik.enable: true
      traefik.http.routers.sabnzbd.entryPoints: https
      traefik.http.routers.sabnzbd.middlewares: auth@file
    environment:
      TZ: ${TZ:?err}
      PGID: ${ID:?err}
      PUID: ${ID:?err}
      UMASK: ${UMASK:?err}
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    driver: bridge
    external: true
