version: "3"
services:
  vault:
    container_name: vault
    image: vaultwarden/server:latest
    expose:
      - 80
    volumes:
      - /opt/appdata/vaultwarden/:/data/
    labels:
      traefik.enable: true
      traefik.http.routers.vault.entryPoints: https
      ## AUTHELIA Auth ##
      # traefik.http.routers.vault.middlewares: auth@file
    environment:
      TZ: Europe/London
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    driver: bridge
    external: true