version: '3'
services:
  vault:
    container_name: vault
    image: vaultwarden/server:latest
    expose:
      - 80
    volumes:
      - ${APP_DIR:?err}/vaultwarden/:/data/
    labels:
      traefik.enable: true
      traefik.http.routers.vault.entryPoints: https
      traefik.http.routers.vault.middlewares: auth@file
    environment:
      TZ: ${TZ:?err}
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    driver: bridge
    external: true