version: '3'
services:
  traefik:
    container_name: traefik
    image: traefik:2.6
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${APP_DIR:?err}/traefik/:/etc/traefik/
    labels:
      traefik.enable: true
      traefik.http.routers.api.rule: Host(`traefik.${DOMAIN:?err}`)
      traefik.http.routers.api.entryPoints: https
      traefik.http.routers.api.service: api@internal
      traefik.http.routers.api.middlewares: auth@file
    environment:
      DOCKER_HOST: dockersocket
      CF_DNS_API_TOKEN: ${CLOUDFLARE_API_TOKEN:?err}
    networks:
      - proxy
      - secure
    restart: unless-stopped
    depends_on:
      - dockersocket

  dockersocket:
    container_name: dockersocket
    image: tecnativa/docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONTAINERS: 1
      POST: 0
    privileged: true
    networks:
      - secure
    restart: unless-stopped

networks:
  proxy:
    driver: bridge
    external: true
  secure:
    driver: bridge
    external: true
