version: '3'
services:
  kutt:
    container_name: kutt
    image: kutt/kutt:latest
    command: ["./wait-for-it.sh", "postgres:5432", "--", "npm", "start"]
    expose:
      - 3000
    env_file:
      - .env
    labels:
      traefik.enable: true
      traefik.http.routers.kutt.entryPoints: https
    environment:
      DB_HOST: postgres
      DB_NAME: kutt
      DB_USER: user
      DB_PASSWORD: pass
      REDIS_HOST: redis     
    networks:
      - proxy
      - secure
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
      
  kutt-redis:
    container_name: kutt-redis
    image: redis:6.0-alpine
    volumes:
      - ${APP_DIR:?err}/kutt/redis:/data
    networks:
      - secure
    restart: unless-stopped

  kutt-postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: kutt
    volumes:
      - ${APP_DIR:?err}/kutt/postgres:/var/lib/postgresql/data
    networks:
      - secure
    restart: unless-stopped

networks:
  proxy:
    driver: bridge
    external: true
  secure:
    driver: bridge
    external: true
