version: '3'
services:
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    expose:
      - 7878
    volumes:
      - ${APP_DIR:?err}/radarr:/config
      - /mnt:/mnt
    labels:
      traefik.enable: true
      traefik.http.routers.radarr.entryPoints: https
      traefik.http.routers.radarr.middlewares: auth@file
    environment:
      TZ: ${TZ:?err}
      PGID: ${ID:?err}
      PUID: ${ID:?err}
      UMASK: ${UMASK:?err}
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    driver: bridge
    external: true