version: '3'
services:
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    expose:
      - 7878
    volumes:
      - ${APP_DIR}/radarr:/config
    labels:
      traefik.enable: true
      traefik.http.routers.radarr.entryPoints: https
      traefik.http.routers.radarr.middlewares: auth@file
    environment:
      TZ: ${TZ}
      PGID: ${ID}
      PUID: ${ID}
      UMASK: ${UMASK}
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    driver: bridge
    external: true