version: '3'
services:
  petio:
    container_name: petio
    image: ghcr.io/petio-team/petio:latest
    expose:
      - 7777
    volumes:
      - ${APP_DIR}/petio/config:/app/api/config
      - ${APP_DIR}/petio/logs:/app/logs
    labels:
      traefik.enable: true
      traefik.http.routers.petio.entryPoints: https
    environment:
      TZ: ${TZ}
    networks:
      - proxy
      - secure
    restart: unless-stopped
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:4.4
    volumes:
      - ${APP_DIR}/mongodb:/data/db
    networks:
      - secure
    restart: unless-stopped

networks:
  proxy:
    driver: bridge
    external: true
  secure:
    driver: bridge
    external: true