version: '3'
services:
  plex-meta-manager:
    container_name: plex-meta-manager
    image: meisnate12/plex-meta-manager:latest
    volumes:
      - ${APP_DIR:?err}/plex-meta-manager:/config
    environment:
      TZ: ${TZ:?err}
      PGID: ${ID:?err}
      PUID: ${ID:?err}
      UMASK: ${UMASK:?err}
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    driver: bridge
    external: true
