version: '3'
services:
  jellyfin:
    container_name: "jellyfin"
    environment:
      TZ: ${TZ:?err}
      PGID: ${ID:?err}
      PUID: ${ID:?err}
      UMASK: ${UMASK:?err}
    image: "jellyfin/jellyfin:latest"
    restart: "unless-stopped"
    networks:
      - proxy
    ports:
      - "8096:8096"
    volumes:
      - "${APP_DIR:?err}/jellyfin:/config:rw"
      - "/mnt:/mnt:ro"
      - "/dev/shm:/transcode:rw"
    devices:
       - /dev/dri:/dev/dri
    labels:
      traefik.enable: true
      traefik.http.routers.jellyfin.entryPoints: https

networks:
  proxy:
    driver: bridge
    external: true
